[package]
name = "rq-testkit"
description = "Fake sysfs/procfs trees for testing The Red Queen"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
tempfile.workspace = true

[lints]
workspace = true
